scalar Date

type User {
  id: ID!
  userName: String!
  email: String!
  createdDate: Date
  updatedDate: Date
}

input RegisterInput {
  userName: String!
  email: String!
  password: String!
}

input LoginInput {
  userName: String!
  password: String!
}
